name: "Deploy nix flake to remote system"
on: workflow_dispatch
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - uses: nicknovitski/nix-develop@v1
    - run: nix flake check --all-systems
    - id: matrix
      run: echo "value=$(make nixos-hosts-json)" >> $GITHUB_OUTPUT
    - run: echo "Configured NixOS hosts: ${{ steps.matrix.outputs.value }}"
  deploy:
    runs-on: ubuntu-latest
    needs: [ setup ]
    strategy:
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
    - run: echo "Deployment for ${{ matrix.value }}"
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - uses: nicknovitski/nix-develop@v1
    # https://tailscale.com/kb/1276/tailscale-github-action
    - name: Connect to Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }} # TODO: Create
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }} # TODO: Create
        tags: tag:ci # TODO: Add tag to tailscale
        ping: ${{ matrix.value }}
    - name: Deploy NixOS flake onto remote system
      run: make remote-os user=root host=${{ matrix.value }} # TODO: Change user
