name: "Deploy nix flake to remote system"
on: 
  workflow_dispatch:
    inputs:
      host:
        description: 'NixOS host to deploy to'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deployment for ${{ github.event.inputs.host }}"
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - uses: nicknovitski/nix-develop@v1
    - run: nix flake check
    # https://tailscale.com/kb/1276/tailscale-github-action
    - name: Connect to Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }} # TODO: Create
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }} # TODO: Create
        tags: tag:ci # TODO: Add tag to tailscale
        ping: ${{ github.event.inputs.host }}
    - name: Deploy NixOS flake onto remote system
      run: make remote-os user=root host=${{ github.event.inputs.host }}
