name: Deploy on merge
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        parameter: [nu, tau]
    steps:
    - name: Check out git repository
      uses: actions/checkout@v5
    - name: Deploy
      uses: ./.github/workflows/deploy.yaml
      with:
        host: ${{ matrix.parameter }}
      secrets:
        TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
